[package]
name = "emed"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ropey = "1.6.1"

[[bin]]
name = "emed"
path = "src/main.rs"

[lib]
name = "emed_core"
path = "src/lib.rs"
