[package]
name = "emed"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
crossterm = "0.29.0"
ropey = "1.6.1"
unicode-width = "0.2.2"

[[bin]]
name = "emed"
path = "src/main.rs"

[lib]
name = "emed_core"
path = "src/lib.rs"
